//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use super::sea_orm_active_enums::QuotaType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub gmail: String,
    pub created_at: DateTime,
    pub name: String,
    pub image: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cloud_account::Entity")]
    CloudAccount,
    #[sea_orm(has_many = "super::quota::Entity", has_one = "super::quota::Entity")]
    Quota,
}

impl Related<super::cloud_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CloudAccount.def()
    }
}

impl Related<super::quota::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Quota.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
