//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use super::sea_orm_active_enums::QuotaType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub gmail: String,
    pub created_at: DateTime,
    pub name: String,
    pub image: Option<String>,
    pub quota_type: QuotaType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
