//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::Provider;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cloud_account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub provider: Provider,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub access_token: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub refresh_token: Option<Vec<u8>>,
    pub is_primary: bool,
    pub created_at: Option<DateTime>,
    pub expires_in: Option<i64>,
    #[sea_orm(unique)]
    pub sub: Option<String>,
    pub token_expired: bool,
    pub updated_at: Option<DateTime>,
    pub image: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
