//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::LinkType;
use super::sea_orm_active_enums::Status;
use super::sea_orm_active_enums::TransferType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "job")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub from_drive: Option<Uuid>,
    pub from_file_id: Option<String>,
    pub is_folder: Option<bool>,
    pub to_drive: Uuid,
    pub to_folder_id: String,
    pub created_at: DateTime,
    pub status: Status,
    pub user_id: Uuid,
    pub size: Option<i64>,
    pub link: Option<String>,
    pub link_type: Option<LinkType>,
    pub transfer_type: TransferType,
    #[sea_orm(
        belongs_to,
        relation_enum = "CloudAccount2",
        from = "from_drive",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub cloud_account_2: HasOne<super::cloud_account::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "CloudAccount1",
        from = "to_drive",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub cloud_account_1: HasOne<super::cloud_account::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
