//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "job")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub from_drive: Uuid,
    pub from_file_id: String,
    pub is_folder: bool,
    pub to_drive: Uuid,
    pub to_folder_id: String,
    pub created_at: DateTime,
    pub status: Status,
    pub user_id: Uuid,
    pub size: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cloud_account::Entity",
        from = "Column::FromDrive",
        to = "super::cloud_account::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CloudAccount2,
    #[sea_orm(
        belongs_to = "super::cloud_account::Entity",
        from = "Column::ToDrive",
        to = "super::cloud_account::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CloudAccount1,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
