//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::QuotaType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "quota")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Float")]
    pub free_quota: i64,
    #[sea_orm(column_type = "Float")]
    pub add_on_quota: i64,
    #[sea_orm(column_type = "Float")]
    pub total_quota: i64,
    #[sea_orm(column_type = "Float")]
    pub used_quota: i64,
    #[sea_orm(column_type = "Float")]
    pub remaining_quota: i64,
    pub quota_type: QuotaType,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
