//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub gmail: String,
    pub created_at: DateTime,
    pub name: String,
    pub image: Option<String>,
    #[sea_orm(unique)]
    pub sub: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cloud_account::Entity")]
    CloudAccount,
    #[sea_orm(has_many = "super::job::Entity")]
    Job,
    #[sea_orm(has_one = "super::quota::Entity")]
    Quota,
}

impl Related<super::cloud_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CloudAccount.def()
    }
}

impl Related<super::job::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Job.def()
    }
}

impl Related<super::quota::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Quota.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
